### PR TITLE
add script to set up DPI on RPI

### PR DESCRIPTION
**Pull request by djulien**
preliminary version.  there are many possible configurations, so some of them might have bugs.

### CODE REVIEW

**Comment by cpinkham** [comment]
We are going to want to have this in the main FPP repository so it is configured and unconfigured automatically.  If you look at how we turn on/off the onboard audio on the Pi for the RPIWS281X channel output, we'll want to do something similar here to setup the DPI output.   Look at /opt/fpp/scripts/functions and setupChannelOutputs() for the details.

**Comment by djulien** [comment]
Oh.  I was assuming this DPI stuff would be an "optional extra" and that it shouldn't be part of the main FPP startup code (and it would just be "yet another" one of the scripts available in the script repo).

In looking at setupChannelOutputs(), it looks like it runs after every boot - is that correct?  I'm more accustomed to using DPI as a 1x persistent install of the device tree overlay (and other config.txt settings), and then it's just there next time the RPi is booted.  I guess I could change it to load dynamically but it seems more fragile that way since there could also be interactions with hdmi ports, framebuffer sizes, etc.  Are those other settings within the design scope of setupChannelOutputs, or will I be compromising the basic software design to put stuff like that in there?

**Comment by djulien** [comment]
Also, I've been trying to squeeze DPI config UI controls onto the Pixel Strings tab as part of ChannelOutputs - should I move them to somewhere else?  (Audio/Video setup has its own separate tab under FPP Settings).

Settings such as FPS, some other frame buffer settings, and an on/off switch for each GPIO pin seemed a little out of place on the Channel Outputs tab.  That's where I'm currently trying to add them, but I can move them if there's somewhere else that is more suitable.  (DPI kind of overlaps GPIO, video, and possibly other functions such as audio, SPI, etc that use GPIO pins)

**Comment by djulien** [comment]
Please cancel/ignore this pull request.  After consultation with FPP developers, decided to use a different approach.

**Pull request closed without merging**
